# elite-contractor-app/docker-compose.yml
version: '3.8' # Specifies the compose file version

services:
  # Define the PostgreSQL database service
  postgres_db:
    image: postgres:15 # Use the official PostgreSQL image, version 15 (or latest)
    container_name: elite_contractor_postgres # A specific name for the container
    restart: always # Automatically restart the container if it stops
    environment:
      # These environment variables configure the PostgreSQL container on first run
      # It's better practice to use variables from a .env file (see next step)
      POSTGRES_DB: ${POSTGRES_DB:-contractor_app_dev} # Database name (uses .env value or default)
      POSTGRES_USER: ${POSTGRES_USER:-contractor_user} # Username (uses .env value or default)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Dominioncontractor} # Password (uses .env value or default)
    ports:
      # Map port 5432 on your host machine to port 5432 inside the container
      # Format: "HOST_PORT:CONTAINER_PORT"
      - "5432:5432"
    volumes:
      # Persist database data outside the container
      # 'pgdata' is a named volume defined below
      # '/var/lib/postgresql/data' is the standard PostgreSQL data directory inside the container
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # Optional: Check if the database is ready
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-contractor_user} -d ${POSTGRES_DB:-contractor_app_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  # Define the named volume for data persistence
  pgdata:
    driver: local # Use the local driver (stores data on your host machine)